---
# dnac_host: 10.22.40.225
# dnac_host: 10.22.40.214
# dnac_host: 172.23.9.219
# dnac_host: 10.195.243.53 
# dnac_host: 10.195.243.38
# dnac_host: 10.195.193.230
# dnac_host: 10.195.243.38

# dnac_host: 10.195.227.14

# dnac_host: 172.23.241.186
dnac_port: 443
# dnac_host: 10.195.227.14
# dnac_host: 172.23.9.219

# dnac_username: admin
# dnac_username: admin
# dnac_username: iacadmin
# dnac_username: mohmshai
# dnac_username: dev_team

# dnac_password: Maglev123
# dnac_password: P@ssword9
# dnac_password: M@glev123
# dnac_password: Mohmad-admin-25
# dnac_password: Admin-Dat-()

dnac_version: 3.1.3.0
# dnac_version: 2.3.7.9
# dnac_version: 2.3.5.3
dnac_verify: False
dnac_debug: True



# dnac_host: 172.23.9.219
# dnac_username: admin
# dnac_password: P@ssword9

dnac_host: 10.22.40.214
dnac_username: admin
dnac_password: M@glev123

# dnac_host: 10.31.102.124
# dnac_username: admin
# dnac_password: Ciscu!123

# dnac_host: 10.195.243.100
# dnac_username: pbalaku2
# dnac_password: RedRose45

