---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Provision a wired device to a site
      cisco.dnac.provision_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - site_name_hierarchy: "Global/USA/SAN-FRANCISCO/BLD_SF"
            management_ip_address: 204.192.13.1
            managed_ap_locations:
              - Global/USA/SAN-FRANCISCO/BLD_SF
              - Global/USA/SAN-FRANCISCO/BLD_SF/FLOOR1
              - Global/USA/SAN-FRANCISCO/BLD_SF/FLOOR2
            provisioning: true
            force_provisioning: true
