---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "input_swim.yml"
    - "credentials.yml"
  tasks:
    - name: Import an image, tag it as golden and load it on device
      cisco.dnac.swim_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - image_distribution_details:
              # image_name: cat9k_iosxe.17.12.02.SPA.bin
              site_name: Global/Chennai/LTTS2
          # - image_activation_details:
          #     site_name: Global/Chennai/LTTS2
          #     device_ip_address: 204.1.2.4